"! Behavior pool of ZI_MATMASS_STAWN (global part, generated by ADT; the logic is in the tab "Local Types",
"! file zbp_i_matmass_stawn.ccimp.abap).
CLASS zbp_i_matmass_stawn DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_matmass_stawn.
ENDCLASS.

CLASS zbp_i_matmass_stawn IMPLEMENTATION.
ENDCLASS.
